import apiEndPoints from "../../constants/apiEndpoints";

const eVoucherTypes = {
  CREATE_EVOUCHER_URL: apiEndPoints.CREATE_EVOUCHER,
  CREATE_EVOUCHER: 'CREATE_EVOUCHER',
  CREATE_EVOUCHER_ERROR: 'CREATE_EVOUCHER_ERROR',

  LIST_EVOUCHER_URL: apiEndPoints.LIST_EVOUCHER,
  LIST_EVOUCHER: 'LIST_EVOUCHER',
  LIST_EVOUCHER_ERROR: 'LIST_EVOUCHER_ERROR',

  UPDATE_EVOUCHER_URL: 'admin/province/updateProvince',
  UPDATE_EVOUCHER: 'UPDATE_EVOUCHER',
  UPDATE_EVOUCHER_ERROR: 'UPDATE_EVOUCHER_ERROR',

  UPDATE_EVOUCHER_STATUS_URL: apiEndPoints.UPDATE_EVOUCHER_STATUS,
  UPDATE_EVOUCHER_STATUS: 'UPDATE_EVOUCHER_STATUS',
  UPDATE_EVOUCHER_STATUS_ERROR: 'UPDATE_EVOUCHER_STATUS_ERROR',

  DETAIL_EVOUCHER: 'DETAIL_EVOUCHER',
};

export default eVoucherTypes;
