const eVoucherTypes = {
  CREATE_EVOUCHER_URL: 'admin/province/createProvince',
  CREATE_EVOUCHER: 'CREATE_EVOUCHER',
  CREATE_EVOUCHER_ERROR: 'CREATE_EVOUCHER_ERROR',
  LIST_EVOUCHER_URL: '/e-vouchers',
  LIST_EVOUCHER: 'LIST_EVOUCHER',
  LIST_EVOUCHER_ERROR: 'LIST_EVOUCHER_ERROR',
  DELETE_EVOUCHER_URL: 'admin/province/deleteProvince',
  DELETE_EVOUCHER: 'DELETE_EVOUCHER',
  DELETE_EVOUCHER_ERROR: 'DELETE_EVOUCHER_ERROR',
  UPDATE_EVOUCHER_URL: 'admin/province/updateProvince',
  UPDATE_EVOUCHER: 'UPDATE_EVOUCHER',
  UPDATE_EVOUCHER_ERROR: 'UPDATE_EVOUCHER_ERROR',
  DETAIL_EVOUCHER: 'DETAIL_EVOUCHER',
};

export default eVoucherTypes;
